# Generated by Django 4.2.15 on 2025-01-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_nf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nome_usuario',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
