# Generated by Django 4.2.15 on 2025-01-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_nf', '0006_remove_notafiscal_criado_em_notafiscal_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='cpf_cnpj',
            field=models.CharField(max_length=18),
        ),
    ]
